use std::errno::{ errno, strerror };
use std::io::{ io };

func main() -> i32 {
    io::stdout().out("[errno] ").out(strerror(errno())).endln();
    return 0;
}